UPPSF-1181 Added runbook
Financial-Times/internal-concordances pull request #11
Opened 2020-09-17 07:36 UTC by powerslider

# Description

## What

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code

## Why

Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2020-09-28 07:29 UTC, karsov requested changes
When fixing the tests it would be more beneficial if we were checking for a `url.Error` and not simply fixing the error strings (which may change in the next Go version)

2020-09-28 07:29 UTC, karsov commented on runbooks/internal-concordances.md
> +Yes
I believe this is not true.

2020-09-28 07:29 UTC, karsov commented on runbooks/internal-concordances.md
> +<table class="table table-bordered" style="border-color: rgb(238, 238, 238); margin: 1em 0px; color: rgb(34, 34, 34); font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helveti
This is not the standard content we use for the Monitoring section.

2020-09-28 07:29 UTC, karsov commented on runbooks/internal-concordances.md
> +<div style="">
This is not the standard content we use for the First Line Troubleshooting section.

2020-09-28 07:45 UTC, ivan-p-nikolov requested changes

2020-10-02 13:35 UTC, ivan-p-nikolov approved these changes

2020-10-02 13:35 UTC, ivan-p-nikolov commented on runbooks/runbook.md
> +- kalin.arsov
Should we stop adding @karsov to runbooks if he is having problems with "managing to many systems"?

2020-10-02 13:51 UTC, karsov approved these changes

2020-10-02 13:53 UTC, karsov commented on runbooks/runbook.md
> +- kalin.arsov
And I can use: https://apigateway.in.ft.com/key-form/developer

2020-10-02 15:02 UTC, merged